language: php
php:
- nightly
- 7.2
- 7.1
matrix:
  allow_failures:
    - php: nightly
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE money_test;'
install: composer install
script:
  - mkdir -p build/logs
  - composer test
after_failure:
  - mysqldump -utravis money_test
after_success:
  - travis_retry php vendor/bin/coveralls -v