shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        command: |
          sudo apt update
          sudo apt install -y libsqlite3-dev zlib1g-dev default-mysql-client
          sudo docker-php-ext-install zip pdo_mysql
    - run: sudo composer self-update
    - restore_cache:
        keys:
          - composer-v1-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
          - composer-v1-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
          - vendor
    - run:
        command: |
          cp config/database{.default,}.php
    - run:
        name: Waiting for MySQL to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MySQL && exit 1
    - run: |
        mkdir -p ~/phpunit
        composer test -- --log-junit ~/phpunit/junit.xml
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit

version: 2

jobs:
  php7.2:
    docker:
      - image: circleci/php:7.2
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_DATABASE: money
          MYSQL_USER: travis
          MYSQL_PASSWORD: really-secret

    <<: *shared
  php7.3:
    docker:
      - image: circleci/php:7.3
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: money
          MYSQL_USER: travis
          MYSQL_PASSWORD: really-secret
    <<: *shared
  php7.4:
    docker:
      - image: circleci/php:7.4
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: money
          MYSQL_USER: travis
          MYSQL_PASSWORD: really-secret
    <<: *shared

workflows:
  version: 2
  workflow:
    jobs:
      - php7.4
      - php7.3
      - php7.2