<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Money</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="<?= $router->pathFor('home') ?>style/main.css">
  </head>
  <body>
    <header>
      <h1>Money</h1>
      <nav>
        <ul>
          <li><a href="<?= $router->pathFor('home') ?>">Home</a></li>
          <li><a href="<?= $router->pathFor('transactions') ?>">Transactions</a></li>
          <li><a href="<?= $router->pathFor('transaction-new') ?>">New Transaction</a></li>
          <li><a href="<?= $router->pathFor('user', [ 'id' => 1 ]) ?>">My Account</a></li>
        </ul>
      </nav>
    </header>
    <main>