<?php

$topHashtags = HashtagQuery::create()
    ->useTransactionHashtagQuery()
    ->withColumn('COUNT(*)', 'Count')
    ->select(array('Transaction', 'Count'))
    ->endUse()
    ->groupByTag()
    ->orderByCount('desc')
    ->limit(5)
    ;
$newestHashtags = HashtagQuery::create()->orderById('desc')->limit(5)->find();


$monthTransactions = TransactionQuery::create()->filterByDate(['min' => new DateTime("first day of this month"), 'max' => new DateTime("last day of this month")])->orderByDate('desc')->find();
$lastMonthTransactions = TransactionQuery::create()->filterByDate(['min' => new DateTime("first day of last month"), 'max' => new DateTime("last day of last month")])->orderByDate('desc')->find();
$yearTransactions = TransactionQuery::create()->filterByDate(['min' => new DateTime("first day of January this year"), 'max' => new DateTime("last day of December this year")])->orderByDate('desc')->find();
$lastYearTransactions = TransactionQuery::create()->filterByDate(['min' => new DateTime("first day of January last year"), 'max' => new DateTime("last day of December last year")])->orderByDate('desc')->find();

// this month
$thisMonthIncoming = 0;
$thisMonthOutgoing = 0;

foreach ($monthTransactions as $t)
{
    if ($t->getValue() > 0)
    {
        $thisMonthIncoming += $t->getValue();
    }
    else
    {
        $thisMonthOutgoing += abs($t->getValue());
    }
}

// last month
$lastMonthIncoming = 0;
$lastMonthOutgoing = 0;

foreach ($lastMonthTransactions as $t)
{
    if ($t->getValue() > 0)
    {
        $lastMonthIncoming += $t->getValue();
    }
    else
    {
        $lastMonthOutgoing += abs($t->getValue());
    }
}

// this year
$thisYearIncoming = 0;
$thisYearOutgoing = 0;

foreach ($yearTransactions as $t)
{
    if ($t->getValue() > 0)
    {
        $thisYearIncoming += $t->getValue();
    }
    else
    {
        $thisYearOutgoing += abs($t->getValue());
    }
}

// last month
$lastYearIncoming = 0;
$lastYearOutgoing = 0;

foreach ($lastYearTransactions as $t)
{
    if ($t->getValue() > 0)
    {
        $lastYearIncoming += $t->getValue();
    }
    else
    {
        $lastYearOutgoing += abs($t->getValue());
    }
}

$months = [];
foreach (['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] as $month)
{
    $transactionsInMonth = TransactionQuery::create()->filterByDate(['min' => new DateTime("first day of $month this year"), 'max' => new DateTime("last day of $month this year")])->orderByDate('desc')->find();
    if ($transactionsInMonth->count() != 0)
    {
        $months[$month]['transactions'] = $transactionsInMonth;
        $months[$month]['income'] = 0;
        $months[$month]['outgoings'] = 0;
        foreach ($transactionsInMonth as $t)
        {
            if ($t->getValue() > 0)
            {
                $months[$month]['income'] += $t->getValue();
            }
            else
            {
                $months[$month]['outgoings'] += abs($t->getValue());
            }
        }
    }
}

$monthsLastYear = [];
foreach (['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] as $month)
{
    $transactionsInMonth = TransactionQuery::create()->filterByDate(['min' => new DateTime("first day of $month last year"), 'max' => new DateTime("last day of $month last year")])->orderByDate('desc')->find();
    if ($transactionsInMonth->count() != 0)
    {
        $monthsLastYear[$month]['transactions'] = $transactionsInMonth;
        $monthsLastYear[$month]['income'] = 0;
        $monthsLastYear[$month]['outgoings'] = 0;
        foreach ($transactionsInMonth as $t)
        {
            if ($t->getValue() > 0)
            {
                $monthsLastYear[$month]['income'] += $t->getValue();
            }
            else
            {
                $monthsLastYear[$month]['outgoings'] += abs($t->getValue());
            }
        }
    }
}


?>

<?php include "header.phtml" ?>
        <h1>Dashboard</h1>

        <h2>Totals</h2>

        <div class="year">
            <h3>Last Year</h3>
            <div class="summary">
                <p>In: <span>£<?= $lastYearIncoming ?></span></p>
                <p>Out: <span>£<?= $lastYearOutgoing ?></span></p>
                <p>Net: <span class="<?= $lastYearIncoming - $lastYearOutgoing < 0 ? 'negative' : '' ?>">£<?= $lastYearIncoming - $lastYearOutgoing ?></span></p>
            </div>
            <?php foreach ($monthsLastYear as $monthName => $monthDetails): ?>
            <div class="month">
                <a href="<?= $router->pathFor('month', [ 'month' => $monthName, 'year' => (new DateTime("first day of January last year"))->format('Y') ]) ?>">
                    <h4>
                        <?= $monthName ?> <?= (new DateTime("first day of January last year"))->format('Y') ?>
                    </h4>
                </a>
                <div class="summary">
                    <p>In: <span>£<?= $monthDetails['income'] ?></span></p>
                    <p>Out: <span>£<?= $monthDetails['outgoings'] ?></span></p>
                    <p>Net: <span class="<?= $monthDetails['income'] - $monthDetails['outgoings'] < 0 ? 'negative' : '' ?>">£<?= $monthDetails['income'] - $monthDetails['outgoings'] ?></span></p>
                </div>
            </div>
            <?php endforeach ?>
        </div>

        <div class="year">
            <h3>This Year</h3>
            <div class="summary">
                <p>In: <span>£<?= $thisYearIncoming ?></span></p>
                <p>Out: <span>£<?= $thisYearOutgoing ?></span></p>
                <p>Net: <span class="<?= $thisYearIncoming - $thisYearOutgoing < 0 ? 'negative' : '' ?>">£<?= $thisYearIncoming - $thisYearOutgoing ?></span></p>
            </div>
            <?php foreach ($months as $monthName => $monthDetails): ?>
            <div class="month">
                <a href="<?= $router->pathFor('month', [ 'month' => $monthName, 'year' => (new DateTime)->format('Y') ]) ?>">
                    <h4>
                        <?= $monthName ?> <?= (new DateTime)->format('Y') ?>
                    </h4>
                </a>
                <div class="summary">
                    <p>In: <span>£<?= $monthDetails['income'] ?></span></p>
                    <p>Out: <span>£<?= $monthDetails['outgoings'] ?></span></p>
                    <p>Net: <span class="<?= $monthDetails['income'] - $monthDetails['outgoings'] < 0 ? 'negative' : '' ?>">£<?= $monthDetails['income'] - $monthDetails['outgoings'] ?></span></p>
                </div>
            </div>
            <?php endforeach ?>
            
        </div>

        <div class="year">
            <h3>Top hashtags</h3>
            <?php foreach ($topHashtags as $tag): ?>
            <div class="tag">
                <a href="<?= $router->pathFor('tag', [ 'tag' => $tag->getTag() ]) ?>">
                    <h3>#<?= $tag->getTag() ?></h3>
                    <small><?= $tag->countTransactions() ?></small>
                </a>
            </div>
            <?php endforeach ?>
            <h3>Newest hashtags</h3>
            <?php foreach ($newestHashtags as $tag): ?>
            <div class="tag">
                <a href="<?= $router->pathFor('tag', [ 'tag' => $tag->getTag() ]) ?>">
                    <h3>#<?= $tag->getTag() ?></h3>
                    <small><?= $tag->countTransactions() ?></small>
                </a>
            </div>
            <?php endforeach ?>
        </div>
        

        <h2>This month</h2>
        <div class="summary">
            <p>Income: £<?= $thisMonthIncoming ?></p>
            <p>Outgoing: £<?= $thisMonthOutgoing ?></p>
        </div>
        <?php foreach ($monthTransactions as $t): ?>
        <div class="transaction <?= $t->getValue() > 0 ? 'income' : 'outgoings' ?> <?= strtolower($t->getAccount()->getName()) ?>">
            <a href="<?= $router->pathFor('transaction', [ 'id' => $t->getId() ]) ?>">
                <h3>£<?= $t->getValue(); ?></h3>
            </a>
            <p>
                <a href="<?= $router->pathFor('transactions', [ 'account' => $t->getAccount()->getName() ]) ?>">
                    <?= $t->getAccount()->getName(); ?>:
                </a>
                <?= $t->getDate('j F Y (D)') ?> - <?= preg_replace('/#(\w+)/', ' <a href="'.$router->pathFor('tag', [ 'tag' => '$1']).'">#$1</a>', $t->getDescription()) ?>
                (<a href="<?= $router->pathFor('transaction-edit', [ 'id' => $t->getId() ]) ?>">edit</a>)
            </p>
        </div>
        <?php endforeach ?>

        <h2>Last month</h2>
        <div class="summary">
            <p>Income: £<?= $lastMonthIncoming ?></p>
            <p>Outgoing: £<?= $lastMonthOutgoing ?></p>
        </div>
        <?php foreach ($lastMonthTransactions as $t): ?>
        <div class="transaction <?= $t->getValue() > 0 ? 'income' : 'outgoings' ?> <?= strtolower($t->getAccount()->getName()) ?>">
            <a href="<?= $router->pathFor('transaction', [ 'id' => $t->getId() ]) ?>">
                <h3>£<?= $t->getValue(); ?></h3>
            </a>
            <p>
                <a href="<?= $router->pathFor('transactions', [ 'account' => $t->getAccount()->getName() ]) ?>">
                    <?= $t->getAccount()->getName(); ?>:
                </a>
                <?= $t->getDate('j F Y (D)') ?> - <?= preg_replace('/#(\w+)/', ' <a href="'.$router->pathFor('tag', [ 'tag' => '$1']).'">#$1</a>', $t->getDescription()) ?>
                (<a href="<?= $router->pathFor('transaction-edit', [ 'id' => $t->getId() ]) ?>">edit</a>)
            </p>
        </div>
        <?php endforeach ?>
        <a href="<?= $router->pathFor('transactions') ?>">
            view all
        </a>

<?php include "footer.phtml" ?>
